### ISSUE TITLE
DISCUSSION: Beam-position conroller IC firmware implementation

### ISSUE THREAD

**Issue by leloup314** [cyclotron-bonn/beamposition_controller#4]
- ADC
    - Use MAX1168 ADCs internal clock mode to read out a sequence of channels at once
    - Implement corresponding functions to:
        - Read individual channel for custom functionality
        - Channels 4 - 7 for 4 input aka single-slit controller operation
        - Channels 0 -7 for 8 input aka double-slit controller operation

**Comment by BelaRincewind** [comment]
That's seems like a valid approach.

**Comment by leloup314** [comment]
Reopening to have discuss further implementations of IC-related firmware ;)

**Comment by leloup314** [comment]
Can you benchmark how long it takes to read 8 channels individually vs. 8 channels via scan?
Run 100 full acquisitions of 8 channels and time how long it takes (you should be able to use the `now` function).

**Comment by BelaRincewind** [comment]
Using an oscilloscope one finds out the following statistics about the ADC speed using these two different modes of acquisition for single- and doubleslit operation:
- individual readout: ~22µs per channel
- scan readout doubleslit: ~9µs per channel (~70µs for all 8)
- scan readout singleslit: ~10µs per channel (~42µs for all 4)

It is hence always feasible to use the scan method. Thus, I propose to redo the method to measure a single channel eight times (there is a method built in for this) in order to get a more precise result by averaging. This can later be used for e.g. calibration.

**Comment by BelaRincewind** [comment]
This issue will be split up into several issues for each IC.
